# -*- coding: utf-8 -*-
"""Real-ESRGAN_finetune

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1996C05t44u2gaHrcfkGsnnHT7cMzQw4_

#Repo Prep

Cloning Repository
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/screen0178/Tugas-akhir.git
# %cd Tugas-akhir
!mkdir datasets
!mkdir -p experiments/pretrained_models
!mkdir results
!mkdir weights
!mkdir inputs

!curl -L https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth \
    -o experiments/pretrained_models/RealESRGAN_x4plus.pth
!curl -L https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRNet_x4plus.pth \
    -o experiments/pretrained_models/RealESRNet_x4plus.pth
!curl -L https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.3/RealESRGAN_x4plus_netD.pth \
    -o experiments/pretrained_models/RealESRGAN_x4plus_netD.pth

"""Installing necessary dependencies"""

!pip install -r requirements.txt
!python setup.py develop

"""Get dataset for finetune (copy from drive)"""

import shutil
import os
from google.colab import drive

drive.mount('/content/drive')

source_path = '/content/drive/MyDrive/SKRIPSI/VID_20240813_073429.mp4'
destination_path = 'inputs/VID_20240813_073429.mp4'

os.makedirs(os.path.dirname(destination_path), exist_ok=True)
shutil.copy2(source_path, destination_path)

"""#Preprocess"""

# Spliting video file to image frame
!python scripts/video_to_frame.py -i inputs/VID_20240813_073429.mp4 \
    -o datasets/custom_tune/hr -n 50

# Generating meta info for image file
!python scripts/generate_meta_info.py --input datasets/custom_tune/hr \
 --root datasets/custom_tune --meta_info datasets/custom_tune/meta_info/meta_info_custom_tune.txt

"""#Finetune Real-ESRGAN"""

# remember to change option to the one you upload
!python realesrgan/train.py -opt options/finetune_realesrgan_x4plus_1000_iter.yml --auto_resume